### PR TITLE
Mail source

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
This introduces a new dependency (`imap-tools`), which seems to be maintained and covers most of low-level IMAP stuff.

When running the code on my own account, I had one or two errors raised, which warrants further inspection.
Most of my emails could be ingested, though.

Do you think, it makes sense to create a subdirectory under the hostname for the alias part of an email account?
After all, a user could have more than one account at that email provider.

What about sanitizing directories? For example, I have some folders containing an `@`.
Is there a utility I can already use? (Otherwise I go with a Regular Expression).

The implementation is inspired by GMail and FitBit sources.

Feedback welcome :-)

### CODE REVIEW

**Comment by kootenpv** [comment]
Looks amazing! I'll review after answering these questions.

> Do you think, it makes sense to create a subdirectory under the hostname for the alias part of an
> email account?
> After all, a user could have more than one account at that email provider.

Yea it makes sense to work with a subdirectory under the input/source. Also, the download/load functions shouldn't take parameters, but in the ingest function we could allow parameters if neccessary (preferably not though)

> What about sanitizing directories

Good question, but no, there are no utility functions for that yet.

**Comment by kootenpv** [comment]
The code looks flawless to me. The only sad part is that the suggested script is not cross-platform.

I am wondering if you expect this will also work with Gmail? Maybe we could list a few examples of settings for different email providers?

And is the issue resolved of that it won't automatically mark emails as read?

Thanks a lot again, this is really fantastic :)

**Comment by Ryuno-Ki** [comment]
> Yea it makes sense to work with a subdirectory under the input/source

Okay, right now, I only create a directory for the IMAP hostname.
Please don't merge until I created a second directory for the mail alias (the part until `@`).

> Also, the download/load functions shouldn't take parameters, but in the ingest function we could allow parameters if neccessary (preferably not though)

Where do you see parameters in `download`?
https://github.com/nostalgia-dev/nostalgia/blob/56042aff12783189551ca5035ab20c941caa4db9/nostalgia/sources/email/__init__.py#L17

>> What about sanitizing directories
> 
> Good question, but no, there are no utility functions for that yet.

My question was rather, whether it's a thing we _should_ do in the first place.
I can go look for a solution then.

> The only sad part is that the suggested script is not cross-platform.

As in „across operating systems”?

> I am wondering if you expect this will also work with Gmail? Maybe we could list a few examples of settings for different email providers?

Sure, we could add examples.
From my time with GoogleMail, I recall that they do weird things with their labels (showing up as duplicated mails in Thunderbird).
But we have a GMail source provider already. I'd defer to that one for GoogleMail (or any other fancy provider, who thinks, it's a good idea to put stuff on top of plain IMAP).
I'd be willing to refactor the code in a way that would make it easy to subclass it.
What exactly would be needed?

> And is the issue resolved of that it won't automatically mark emails as read?

As long as you pass the flag in
https://github.com/nostalgia-dev/nostalgia/blob/56042aff12783189551ca5035ab20c941caa4db9/nostalgia/sources/email/export.py#L33
mails won't be marked as read (but the default value is surprisingly `True`)

> Thanks a lot again, this is really fantastic :)

I was surprised myself, that it only took one evening!

**Comment by kootenpv** [comment]
> Yea it makes sense to work with a subdirectory under the input/source

Okay, right now, I only create a directory for the IMAP hostname.
Please don't merge until I created a second directory for the mail alias (the part until `@`).

> Also, the download/load functions shouldn't take parameters, but in the ingest function we could allow parameters if neccessary (preferably not though)

Where do you see parameters in `download`?
https://github.com/nostalgia-dev/nostalgia/blob/56042aff12783189551ca5035ab20c941caa4db9/nostalgia/sources/email/__init__.py#L17

**I more meant as some background, not saying you actually made that mistake** 😅

>> What about sanitizing directories
> 
> Good question, but no, there are no utility functions for that yet.

My question was rather, whether it's a thing we _should_ do in the first place.
I can go look for a solution then.

**Could use something like `re.sub('[^\w_.)( -]', '', any_string)`**

> The only sad part is that the suggested script is not cross-platform.

As in „across operating systems”?

**Yea that's what I meant, but I think we can simply for now just provide this as inspiration**

> I am wondering if you expect this will also work with Gmail? Maybe we could list a few examples of settings for different email providers?

Sure, we could add examples.
From my time with GoogleMail, I recall that they do weird things with their labels (showing up as duplicated mails in Thunderbird).
But we have a GMail source provider already. I'd defer to that one for GoogleMail (or any other fancy provider, who thinks, it's a good idea to put stuff on top of plain IMAP).
I'd be willing to refactor the code in a way that would make it easy to subclass it.
What exactly would be needed?

**I am not sure. But maybe we could test it with a provider we don't have, like outlook/hotmail. You think it would work? I could maybe try. **

> And is the issue resolved of that it won't automatically mark emails as read?

As long as you pass the flag in
https://github.com/nostalgia-dev/nostalgia/blob/56042aff12783189551ca5035ab20c941caa4db9/nostalgia/sources/email/export.py#L33
mails won't be marked as read (but the default value is surprisingly `True`)

**Yea, that's really horrible, hope it did not cause too much damage to your inbox.**

> Thanks a lot again, this is really fantastic :)

I was surprised myself, that it only took one evening!

**I think you really know how to use nostalgia! So from that moment I indeed I think it is 1 source per evening :) I really don't have much inspiration for my own data at this point.**

**Comment by Ryuno-Ki** [comment]
> Please don't merge until I created a second directory for the mail alias (the part until `@`).

Done.

The only error I ran into locally (`$VARIABLES` inserted by me) is:

```py
from nostalgia.sources.email import Email
Email.download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$PROJECT_ROOT/nostalgia/sources/email/__init__.py", line 23, in download
    imap_export.walk_folders()
  File "$PROJECT_ROOT/nostalgia/sources/email/export.py", line 58, in walk_folders
    mails = self.walk_folder(mailbox, folder_name)
  File "$PROJECT_ROOT/nostalgia/sources/email/export.py", line 40, in walk_folder
    "to": msg.to,
  File "$VENV_ROOT/lib64/python3.6/site-packages/imap_tools/message.py", line 118, in to
    return tuple(i['email'] for i in self.to_values)
  File "$VENV_ROOT/lib64/python3.6/site-packages/imap_tools/message.py", line 112, in to_values
    return parse_email_addresses(self.obj['To'] or '')
  File "$VENV_ROOT/lib64/python3.6/site-packages/imap_tools/utils.py", line 72, in parse_email_addresses
    for raw_name, email in getaddresses([raw_header]):
  File "/usr/lib64/python3.6/email/utils.py", line 112, in getaddresses
    all = COMMASPACE.join(fieldvalues)
TypeError: sequence item 0: expected str instance, Header found
```

I think, a bad mail in my inbox.
I'll submit a patch afterwards, okay?

> > > > What about sanitizing directories
> > > 
> > > Good question, but no, there are no utility functions for that yet.
> > 
> > My question was rather, whether it's a thing we _should_ do in the first place.
> > I can go look for a solution then.
> 
> Could use something like `re.sub('[^\w_.)( -]', '', any_string)`

I went with this approach instead:

https://github.com/django/django/blob/796be5901a67da44e251e092641682cb2d778176/django/utils/text.py#L221-L232

Those devs should have some experience by now :-)

> > > The only sad part is that the suggested script is not cross-platform.
> > 
> > As in „across operating systems”?
> 
> Yea that's what I meant, but I think we can simply for now just provide this as inspiration

Hm, I thought I would have avoided using `/` and that like and defer to Python instead.
If you spot something, let me know and I'll submit a patch.
 
> > > I am wondering if you expect this will also work with Gmail? Maybe we could list a few examples of settings for different email providers?
> > 
> > Sure, we could add examples.
> 
> I am not sure. But maybe we could test it with a provider we don't have, like outlook/hotmail. You think it would work? I could maybe try.

As long as the mail provider is using standard IMAP, it should work™.

I mean [I had unpleasant experiences](https://www.ghacks.net/2017/08/07/openmailbox-alternatives-after-owner-change/) in the past.
Looks like the [site](https://web.archive.org/web/20191127222637/https://www.openmailbox.org/) is down since a year. There was next to no way to save your mails gone hostage.

> Yea, that's really horrible, hope it did not cause too much damage to your inbox.

I never read the mails in my inbox that fast!
Luckily, I did not told Python to walk the folders, when testing it.

> I think you really know how to use nostalgia! So from that moment I indeed I think it is 1 source per evening :) I really don't have much inspiration for my own data at this point.

Well, let's see. I have some more sources in mind. One after the other. Perhaps it can attract more contributors?

**Comment by kootenpv** [comment]
Thanks for wrapping it up! Very clear. When I meant cross platform, I was actually only referring to the suggested script on how to ingest the emails :)

> I never read the mails in my inbox that fast!

Hahah 😂

> Well, let's see. I have some more sources in mind. One after the other. Perhaps it can attract more contributors?

Definitely hope so!

And indeed, please provide the patch afterwards.

Also, since Nickolay is less active, I'll squash and merge. Thanks for another wonderful contribution!

**Review by kootenpv — APPROVED** [review]

**Pull request merged**
