### PR TITLE
First iteration on Twitter data source

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
This is my first contribution to Nostalgia code base.
As such, I'm likely need to make some tweeks.

Big shoutout to @kootenpv, who was a tremendous help on Discord!

The Parquet is generated from a Twitter export for now.
For some reason, the data isn't shown in the timeline (I assume, it's because of missing column name?).

I oriented on #11 for generating it.

Feedback welcome.

### CODE REVIEW

**Comment by kootenpv** [comment]
This really seems perfect! I would merge this as is. It actually is a good start for #2 (not sure if it is possible to add private messaging too). It's also fine to create a new PR that we can merge quickly for any other kinds of changes, but it's impressive that the first PR is immediately working for me :)

Thanks a lot!

**Review by kootenpv — DISMISSED** [review]

**Comment by kootenpv** [comment]
@NickolayVasilishin Hey man how are you, could you also approve :)?

**Review by NickolayVasilishin — DISMISSED** [review]

**Comment by NickolayVasilishin** [comment]
That looks great thanks for the contribution!
I would just ask you to add newlines for each file

**Comment by Ryuno-Ki** [comment]
Will do.
DMs will be ingested in another PR then.

Let me have lunch first, please :-)

**Comment by Ryuno-Ki** [comment]
I ran black on the source code.
Please re-check, @NickolayVasilishin @kootenpv 

The check fails over:

> git checkout --progress --force twitter-source
> error: pathspec 'twitter-source' did not match any file(s) known to git
> ##[error]Git checkout failed with exit code: 1
> ##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.263.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.

Is it something I need to fix?

**Comment by kootenpv** [comment]
I am not sure what happened with Github Actions :thinking: 

@daikikatsuragawa Do you have any idea what's up with it?

**Review by kootenpv — APPROVED** [review]

**Comment by kootenpv** [comment]
In any case, let's not allow the PR to hang on this. I approved. Now @NickolayVasilishin

**Review by NickolayVasilishin — APPROVED** [review]

**Pull request merged**
