### PR TITLE
Apply black

### PR DESCRIPTION
**Pull request by daikikatsuragawa**
Apply Python code formatter [black](https://github.com/psf/black) with the line length of 120. (#28)

If 100 is better, I will fix it.

### CODE REVIEW

**Comment by kootenpv** [comment]
This is great... I guess we should also add a precommit hook or add CI.

**Review by kootenpv — APPROVED** [review]

**Review by kootenpv — DISMISSED** [review]

**Review by NickolayVasilishin — DISMISSED** [review]

**Comment by kootenpv** [comment]
@daikikatsuragawa Great contribution! Any idea how we could add this on commits? Maybe with Github Actions?

**Comment by daikikatsuragawa** [comment]
> @daikikatsuragawa Great contribution! Any idea how we could add this on commits? Maybe with Github Actions?

Support only when "pull request" is executed.

**Comment by kootenpv** [comment]
That is true, this should be first. Can merge.

**Comment by daikikatsuragawa** [comment]
Probably executed on the next pull request.

**Comment by kootenpv** [comment]
Sounds great! By the way, if you want, please join us :)!

Slack: https://bit.ly/2Yre09N
Discord: https://discord.gg/nJQfM2A

**Pull request merged**
